package com.timora.app.model.enums;

public enum Permission {
    BOOKING_CREATE,
    BOOKING_READ,
    BOOKING_UPDATE,
    BOOKING_DELETE,

    AVAILABILITY_CREATE,
    AVAILABILITY_READ,
    AVAILABILITY_UPDATE,
    AVAILABILITY_DELETE,

    SERVICE_CREATE,
    SERVICE_READ,
    SERVICE_UPDATE,
    SERVICE_DELETE,

    CUSTOMER_CREATE,
    CUSTOMER_READ,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
}